<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeServices.Identity.Application\HomeServices.Identity.Application.csproj" />
    <ProjectReference Include="..\HomeServices.Identity.Domain\HomeServices.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\shared\HomeServices.Shared\HomeServices.Shared.csproj" />
  </ItemGroup>

</Project>
